services:
  backend-app:
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
  postgres:
    image: postgres:15-alpine
    container_name: rmp_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - rmp_data:/var/lib/postgresql/data
    networks:
      - rmp_network

  redis:
    image: redis:7.0-alpine
    container_name: redis_container_rmp
    ports:
      - "6379:6379"
    volumes:
      - rmp_redis_data:/data
    networks:
      - rmp_network

volumes:
  rmp_data:
  rmp_redis_data:

networks:
  rmp_network:
    driver: bridge
